[project]
name = "position-nn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "matplotlib>=3.10.0",
    "pandas>=2.2.3",
    "pyneurgen>=0.3.1",
    "torch>=2.5.1",
]
